"""
Compton differential cross-section kernels: power series, asymptotic series, quadrature, and adaptive solver
"""
from __future__ import annotations
import compton_matrix._compton_common
import numpy
import numpy.typing
import typing
__all__: list[str] = ['ComptonKernelAsymptoticSeries', 'ComptonKernelQuadrature', 'ComptonKernelSolver', 'ComptonPowerSeries', 'QuadratureForm', 'ehat_cf', 'gauss_laguerre_rule', 'kappa_ratio', 'scaled_K1', 'scaled_K2']
class ComptonKernelAsymptoticSeries:
    def __init__(self, high_precision: bool = False, eps_rel: typing.SupportsFloat | typing.SupportsIndex = 1e-08, n_min: typing.SupportsInt | typing.SupportsIndex = 4, n_max: typing.SupportsInt | typing.SupportsIndex = 200) -> None:
        ...
    def dsigma_E_dT(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime: typing.SupportsFloat | typing.SupportsIndex, xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> compton_matrix._compton_common.ComptonResult:
        ...
    def dsigma_E_dT_precision_check(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime: typing.SupportsFloat | typing.SupportsIndex, xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def dsigma_E_dT_vec(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime_arr: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> tuple:
        ...
    def sigma_E(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime: typing.SupportsFloat | typing.SupportsIndex, xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> compton_matrix._compton_common.ComptonResult:
        ...
    def sigma_E_precision_check(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime: typing.SupportsFloat | typing.SupportsIndex, xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def sigma_E_vec(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime_arr: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> tuple:
        ...
class ComptonKernelQuadrature:
    def __init__(self, NL: typing.SupportsInt | typing.SupportsIndex = 64, form: QuadratureForm = ...) -> None:
        ...
    def dsigma_E_dT(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime: typing.SupportsFloat | typing.SupportsIndex, xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> compton_matrix._compton_common.ComptonResult:
        ...
    def dsigma_E_dT_vec(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime_arr: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> tuple:
        ...
    def sigma_E(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime: typing.SupportsFloat | typing.SupportsIndex, xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> compton_matrix._compton_common.ComptonResult:
        ...
    def sigma_E_vec(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime_arr: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> tuple:
        ...
class ComptonKernelSolver:
    def __init__(self, asymp_tau_alpha_threshold: typing.SupportsFloat | typing.SupportsIndex = 0.035, power_series_self_tol: typing.SupportsFloat | typing.SupportsIndex = 1e-07, asymp_self_tol: typing.SupportsFloat | typing.SupportsIndex = 1e-07, dd_power_series_self_tol: typing.SupportsFloat | typing.SupportsIndex = 0.5, dd_asymp_self_tol: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def dsigma_E_dT(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime: typing.SupportsFloat | typing.SupportsIndex, xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> compton_matrix._compton_common.ComptonResult:
        ...
    def dsigma_E_dT_vec(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime_arr: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> tuple:
        ...
    def sigma_E(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime: typing.SupportsFloat | typing.SupportsIndex, xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> compton_matrix._compton_common.ComptonResult:
        ...
    def sigma_E_vec(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime_arr: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> tuple:
        ...
class ComptonPowerSeries:
    def __init__(self, high_precision: bool = False, eps_rel: typing.SupportsFloat | typing.SupportsIndex = 1e-08, n_min: typing.SupportsInt | typing.SupportsIndex = 4, n_max: typing.SupportsInt | typing.SupportsIndex = 500) -> None:
        ...
    def dsigma_E_dT(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime: typing.SupportsFloat | typing.SupportsIndex, xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> compton_matrix._compton_common.ComptonResult:
        ...
    def dsigma_E_dT_precision_check(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime: typing.SupportsFloat | typing.SupportsIndex, xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def dsigma_E_dT_vec(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime_arr: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> tuple:
        ...
    def sigma_E(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime: typing.SupportsFloat | typing.SupportsIndex, xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> compton_matrix._compton_common.ComptonResult:
        ...
    def sigma_E_precision_check(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime: typing.SupportsFloat | typing.SupportsIndex, xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def sigma_E_vec(self, E: typing.SupportsFloat | typing.SupportsIndex, E_prime_arr: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], xi: typing.SupportsFloat | typing.SupportsIndex, T: typing.SupportsFloat | typing.SupportsIndex, Ne: typing.SupportsFloat | typing.SupportsIndex) -> tuple:
        ...
class QuadratureForm:
    """
    Members:
    
      PostIBP
    
      PreIBP
    """
    PostIBP: typing.ClassVar[QuadratureForm]  # value = <QuadratureForm.PostIBP: 0>
    PreIBP: typing.ClassVar[QuadratureForm]  # value = <QuadratureForm.PreIBP: 1>
    __members__: typing.ClassVar[dict[str, QuadratureForm]]  # value = {'PostIBP': <QuadratureForm.PostIBP: 0>, 'PreIBP': <QuadratureForm.PreIBP: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
def ehat_cf(m: typing.SupportsInt | typing.SupportsIndex, x: typing.SupportsFloat | typing.SupportsIndex) -> float:
    """
    Scaled exponential integral via continued fraction: Ehat_m(x) = exp(x) * E_m(x)
    """
def gauss_laguerre_rule(N: typing.SupportsInt | typing.SupportsIndex) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64]]:
    """
    Compute N-point Gauss-Laguerre nodes and weights
    """
def kappa_ratio(tau: typing.SupportsFloat | typing.SupportsIndex) -> float:
    """
    Returns K_1(1/tau) / K_2(1/tau)
    """
def scaled_K1(x: typing.SupportsFloat | typing.SupportsIndex) -> float:
    """
    Returns kve(1, x) = exp(x) * K_1(x)
    """
def scaled_K2(x: typing.SupportsFloat | typing.SupportsIndex) -> float:
    """
    Returns kve(2, x) = exp(x) * K_2(x)
    """
